name: Veracode DAST Scan Submission

on:
  push:
    branches:
      - 'main'

jobs:

    Prepare:
        runs-on: ubuntu-latest
        steps:
            # Prepare environment for scan submission
            - name: Test print
              run: echo "PREP - Prueba de preparación de ambiente"

    VeracodeDAST:
        needs: Prepare
        runs-on: ubuntu-latest
        steps:
            # Executes DAST Scan submission
            - name: Veracode DAST Scan
              run: echo "VERACODEDAST - Prueba de ejecución de pipeline de DAST"
