name: Veracode DAST Scan Submission

on:
  push:
    branches:
      - 'main'

env:
  VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_ID }}
  VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_API_KEY }}

jobs:

    VeracodeDAST:
        runs-on: ubuntu-latest
        steps:
            # Install Veracode CLI
            - name: Install Veracode CLI
              run: |
                curl -fsS -O https://tools.veracode.com/veracode-cli/install
                chmod +x ./install
                ./install
                ./veracode version

            # Execute DAST Scan submission
            - name: Veracode DAST Scan
              run: |
                echo "Submitting Veracode DAST Scan"
                ./veracode dynamic scan --webhook 4088954e-5c61-4714-a099-535825ed1074
